config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "signin#index"

  post '/signin/authenticate', to: "signin#authenticate"
  get '/signup', to: "register#new"
  get '/loggedin', to: "loggedin#index"
  get '/logout', to: "loggedin#logout"

  resources :registers, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User
  include ActiveModel::Model
  MAX_EMAIL_LOCAL_PART_CHARS = 64
  MAX_EMAIL_DOMAIN_CHARS = 128

  attr_accessor :name, :email, :password

  validates :name, presence: true, length: { minimum: 5, maximum: 128, message: "must have at least 5 letters." }
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 10, maximum: 72, message: 'must have at least 10 characters.' }
  validate :password_complexity
  validate :email_complexity
  validate :email_uniqueness

  def to_hash
    { email.to_sym => { name:, password: encrypt_password } }
  end

  def self.find_by(email)
    return if email.nil?

    data = $redis.hgetall(email)
    return if data.empty?

    new(data)
  end

  def authenticate(given_password)
    BCrypt::Password.new(password).is_password?(given_password) && self
  end

  def save
    if valid?
      $redis.hset(email, "email", email, "name", name, "password", encrypt_password)
      true
    else
      false
    end
  end

  private

  def encrypt_password
    BCrypt::Password.create(password)
  end

  def email_uniqueness
    errors.add(:email, 'already been registered. Try another one!') if self.class.find_by(email)
  end

  def password_complexity
    return unless password.present?

    unless password.match?(/[A-Z].*[A-Z]/) &&
           password.match?(/[a-z].*[a-z]/) && 
           password.match?(/[!@#$%^&*()_+{}\[\]:;<>,.?~\\-]/) &&
           password.match?(/[0-9]/)
      errors.add(:password, 'must include at least 2 uppercase letters, 2 lowercase letters, 2 special characters, and 1 number.')
    end
  end

  def email_complexity
    return unless email.present?
  
    unless email.match?(/[a-zA-Z0-9!#$%&'*+\-\/=?^_`{|}~]+@[a-zA-Z0-9.-]+\.[a-zA-Z]/)
      return errors.add(:email, 'must be in the format local-part@domain.TLD')
    end

    local_part, domain = email.split("@")

    unless local_part.length <= MAX_EMAIL_LOCAL_PART_CHARS
      errors.add(:email, "local part can only contain a maximum of #{MAX_EMAIL_LOCAL_PART_CHARS} characters.")
    end


    unless domain.length <= MAX_EMAIL_DOMAIN_CHARS
      errors.add(:email, "domain can only contain a maximum of #{MAX_EMAIL_DOMAIN_CHARS} characteres")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_current_user(user)
    session[:user_email] = user.email
  end

  def current_user
    @current_user ||= User.find_by(session[:user_email])
  end

  def authenticate_user(user_params)
    user = User.find_by(user_params[:email]).try(:authenticate, user_params[:password])

    if user
      reset_session
      set_current_user(user)
    else
      reset_session
    end
  end

  def authenticated?
    redirect_to root_path unless current_user
  end
end

app/controllers/loggedin_controller.rb
class LoggedinController < ApplicationController
  before_action :authenticated?

  def index
    user_ip_data = IpDataService.call(request.remote_ip)

    @data = if user_ip_data.dig("bogon")
              fake_data
            else
              {
                name: current_user.name,
                email: current_user.email,
                city: user_ip_data.dig("city"),
                region: user_ip_data.dig("region"),
                country: user_ip_data.dig("country")
              }
            end
  end

  def logout
    reset_session
    redirect_to root_path, notice: 'User successfully loggout.'
  end

  private

  def fake_data
    {
      name: current_user.name,
      email: current_user.email,
      city: "Salvador",
      region: "Northeast",
      country: "Brazil"
    }
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'User successfully created. Sign-in now!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  def index
    return render :index unless current_user

    redirect_to loggedin_path
  end

  def authenticate
    if authenticate_user(user_params)
      redirect_to loggedin_path
    else
      flash.now[:alert] = "Email or password are incorrect."
      render :index, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeebeanTestProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <% if type == "notice" %>
        <div class="alert alert-success text-center">
          <%= message %>
        </div>
      <% elsif type == "alert" %>
        <div class="alert alert-danger text-center">
          <%= message %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/loggedin/index.html.erb
<div class="container mt-5">
  <table class="table table-striped">
    <tbody>
      <% @data.each_with_index do |(key, value), index| %>
        <tr class="<%= index.even? ? 'table-light' : 'table-white' %>">
          <td><%= key %></td>
          <td><%= value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= link_to "Logout", logout_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/registers/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger mb-4">
    <h4><%= pluralize(@user.errors.count, "error") %> founded:</h4>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/registers/new.html.erb
<h1 class="text-center mt-5 mb-4">User Registration</h1>

<%= form_with(model: @user, url: registers_path, local: true, html: { class: 'mx-auto mt-4', style: 'max-width: 400px;' }) do |form| %>
  <%= render partial: 'errors' %>
  
  <div class="form-group mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="d-flex justify-content-center gap-3">
    <div class="form-actions text-center">
      <%= form.submit 'Create', class: 'btn btn-primary' %>
    </div>
    <div class="form-actions text-center">
      <%= link_to 'Back', { controller: 'signin', action: 'index' }, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/signin/index.html.erb
<%= content_tag :div, class: 'container d-flex align-items-center justify-content-center vh-100' do %>
  <%= form_with(model: User.new, url: '/signin/authenticate', method: 'post', local: true, class: 'text-center') do |form| %>
    <%= form.label :email, 'E-mail' %>
    <%= form.email_field :email, class: 'form-control mb-3', required: true, id: 'emailField' %>

    <%= form.label :password, 'Password' %>
    <%= form.password_field :password, class: 'form-control mb-3', required: true %>

    <div class="d-flex justify-content-center gap-3">
      <%= form.submit 'Sign-in', class: 'btn btn-primary', id: 'submitButton' %>
      <%= link_to 'Sign-up', { controller: 'registers', action: 'new' }, class: 'btn btn-secondary' %>
    </div>
  <% end %>
<% end %>